vim.keymap.set("n", "[b", function()
  vim.api.nvim_command("bprev")
end)
vim.keymap.set("n", "]b", function()
  vim.api.nvim_command("bnext")
end)
vim.keymap.set("n", "[B", function()
  vim.api.nvim_command("bfirst")
end)
vim.keymap.set("n", "]B", function()
  vim.api.nvim_command("blast")
end)

vim.keymap.set("n", "[T", function()
  vim.api.nvim_command("tabprev")
end)
vim.keymap.set("n", "]T", function()
  vim.api.nvim_command("tabnext")
end)
vim.keymap.set("n", "[T", function()
  vim.api.nvim_command("tabfirst")
end)
vim.keymap.set("n", "]T", function()
  vim.api.nvim_command("tablast")
end)

vim.keymap.set("n", "]d", function()
  vim.lsp.buf.definition()
end)
vim.keymap.set("n", "]r", function()
  vim.lsp.buf.references()
end)
vim.keymap.set("n", "]i", function()
  vim.lsp.buf.implementation()
end)

vim.keymap.set("n", "<leader>j", "<C-i>")
vim.keymap.set("n", "<leader>k", "<C-o>")
