# [前提]
# echo "source ~/.config/tmux/.tmux.conf" > ~/.tmux.conf

# 設定ファイルのリロード
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# プレフィクスの変更
unbind C-b
unbind C-f
set-option -g prefix C-f

# paneの移動
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# マウス操作を有効化
set -g mouse on
